/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "filehandler_constants.h"

namespace FileHandler {

const filehandlerConstants g_filehandler_constants;

filehandlerConstants::filehandlerConstants() {
}

} // namespace

