/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef filehandler_CONSTANTS_H
#define filehandler_CONSTANTS_H

#include "filehandler_types.h"

namespace FileHandler {

class filehandlerConstants {
 public:
  filehandlerConstants();

};

extern const filehandlerConstants g_filehandler_constants;

} // namespace

#endif
