apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: flaskcontainer
spec:
  selector:
    matchLabels:
      app: flaskcontainer
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: flaskcontainer
    spec:
      containers:
      - name: flaskcontainer 
        image: nipun/flaskconatiner:1.0
        ports:
        - containerPort: 5000
        imagePullPolicy: Never
