apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: memcached
spec:
  selector:
    matchLabels:
      app: memcached
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: memcached
    spec:
      containers:
      - name: memcached 
        image: nipun/memcached:alpine3.8
        ports:
        - containerPort: 11211
        imagePullPolicy: Never
