/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef remotecommand_CONSTANTS_H
#define remotecommand_CONSTANTS_H

#include "remotecommand_types.h"

namespace RemoteCommand {

class remotecommandConstants {
 public:
  remotecommandConstants();

};

extern const remotecommandConstants g_remotecommand_constants;

} // namespace

#endif
