/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "remotecommand_constants.h"

namespace RemoteCommand {

const remotecommandConstants g_remotecommand_constants;

remotecommandConstants::remotecommandConstants() {
}

} // namespace

